# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (C) 2020 Daniel Thompson
"""Shared manifest for applications that work well on a 240x240 display."""

manifest = (
    'fonts/__init__.py',
    # 'fonts/clock.py',
    # 'fonts/clock_dual.py',
    'fonts/sans18.py',
    'fonts/sans24.py',
    'fonts/sans28.py',
    'fonts/sans36.py',
    'fonts/sans18.py',
    'steplogger.py',
    'wash/app/alarmapp.py',
    'wash/app/baseapplication.py',
    'wash/app/basewatchface.py',
    'wash/app/crashapp.py',
    'wash/app/heartapp.py',
    'wash/app/iapplication.py',
    'wash/app/isettingsapplication.py',
    'wash/app/launcherapp.py',
    'wash/app/nightmodeapp.py',
    'wash/app/notificationapp.py',
    'wash/app/pagerapp.py',
    'wash/app/settingsapp.py',
    'wash/app/softwareapp.py',
    'wash/app/system/appidentifier.py',
    'wash/app/system/settings/about.py',
    'wash/app/system/settings/datetimeconfig.py',
    'wash/app/system/settings/systemconfig.py',
    'wash/app/system/settings/themeconfig.py',
    'wash/app/torchapp.py',
    'wash/app/user/settings/heartconfig.py',
    'wash/app/user/settings/torchconfig.py',
    'wash/app/watchface/battri.py',
    'wash/app/watchface/settings/watchfaceconfig.py',
    'wash/brightnesslevel.py',
    'wash/datavault.py',
    'wash/haxe.py',
    'wash/icon/AppIcon.py',
    'wash/icon/BatteryIcon.py',
    'wash/icon/BleStatusIcon.py',
    'wash/icon/BombIcon.py',
    'wash/icon/CheckboxIcon.py',
    'wash/icon/DownArrow.py',
    'wash/icon/Knob.py',
    'wash/icon/NotificationIcon.py',
    'wash/icon/PlugIcon.py',
    'wash/icon/UpArrow.py',
    'wash/manager.py',
    'wash/notificationcontent.py',
    'wash/notificationlevel.py',
    'wash/theme.py',
    'wash/util/ble.py',
    'wash/util/int16.py',
    'wash/util/timeutils.py',
    'wash/widgets/batterymeter.py',
    'wash/widgets/button.py',
    'wash/widgets/checkbox.py',
    'wash/widgets/clock.py',
    'wash/widgets/colorpicker.py',
    'wash/widgets/confirmationview.py',
    'wash/widgets/iwidget.py',
    'wash/widgets/notificationbar.py',
    'wash/widgets/pinhandler.py',
    'wash/widgets/scrollindicator.py',
    'wash/widgets/slider.py',
    'wash/widgets/spinner.py',
    'wash/widgets/statusbar.py',
    'wash/widgets/togglebutton.py'
)
